Repository bitcoindevkit/bdk_wallet, pull requests merged in 2025-06, with the labels that each got.

#255 Release v2.0.0
  wallet/Cargo.toml
Labels: release

#256 chore: bump dev version to 2.1.0-alpha.0
  wallet/Cargo.toml
Labels: chore

#266 Bump `bitcoin` dependency requirement to v0.32.6 to reflect used API
  wallet/Cargo.toml
Labels: dependencies

#268 feat: add `justfile`
  .github/pull_request_template.md
  README.md
  justfile
Labels: chore
