Repository bitcoindevkit/bdk_wallet, pull requests merged in 2025-05, with the labels that each got.

#208 deps!: update `bdk_chain` to 0.22.0
  ci/pin-msrv.sh
  examples/example_wallet_electrum/Cargo.toml
  examples/example_wallet_electrum/src/main.rs
  examples/example_wallet_esplora_async/Cargo.toml
  examples/example_wallet_esplora_blocking/Cargo.toml
  examples/example_wallet_esplora_blocking/src/main.rs
  examples/example_wallet_rpc/Cargo.toml
  examples/example_wallet_rpc/src/main.rs
  wallet/Cargo.toml
  wallet/README.md
  wallet/src/test_utils.rs
  wallet/src/wallet/mod.rs
  wallet/src/wallet/persisted.rs
  wallet/tests/wallet.rs
Labels: dependencies, api

#215 Chore: migrate library version naming convention on master
  wallet/Cargo.toml
Labels: chore

#198 docs(wallet): provide guidance on use of `ChangeSet`
  wallet/src/wallet/changeset.rs
  wallet/src/wallet/mod.rs
Labels: documentation

#200 ci: Add Ubuntu 24.04 ARM support for build-test job
  .github/workflows/cont_integration.yml
Labels: chore

#8 Add zizmor github actions security analysis workflow
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
  .github/workflows/cron-update-rust.yml
  .github/workflows/zizmor.yml
  wallet/src/wallet/signer.rs
  wallet/tests/psbt.rs
Labels: github_actions

#213 chore: create and apply rustfmt.toml
  .github/pull_request_template.md
  .github/workflows/cont_integration.yml
  rustfmt.toml
  wallet/examples/compiler.rs
  wallet/examples/policy.rs
  wallet/src/descriptor/checksum.rs
  wallet/src/descriptor/dsl.rs
  wallet/src/descriptor/mod.rs
  wallet/src/descriptor/policy.rs
  wallet/src/descriptor/template.rs
  wallet/src/keys/mod.rs
  wallet/src/psbt/mod.rs
  wallet/src/types.rs
  wallet/src/wallet/changeset.rs
  wallet/src/wallet/coin_selection.rs
  wallet/src/wallet/mod.rs
  wallet/src/wallet/persisted.rs
  wallet/src/wallet/signer.rs
  wallet/src/wallet/tx_builder.rs
  wallet/tests/wallet.rs
Labels: chore

#214 feat(test): add legacy descriptor tests
  wallet/src/test_utils.rs
  wallet/tests/wallet.rs
Labels: tests

#223 feat(test-utils)!: use `bitcoin::Amount` instead of `u64` on tests
  wallet/src/test_utils.rs
  wallet/src/wallet/export.rs
  wallet/src/wallet/tx_builder.rs
  wallet/tests/wallet.rs
Labels: api, tests

#232 fix: Validate prevouts in `get_psbt_input`
  wallet/src/wallet/error.rs
  wallet/src/wallet/mod.rs
Labels: bug

#201 Bring back TxDetails
  wallet/src/wallet/mod.rs
  wallet/src/wallet/utils.rs
  wallet/tests/wallet.rs
Labels: new feature

#247 deps: Update `bdk_chain` to 0.23.0
  examples/example_wallet_electrum/Cargo.toml
  examples/example_wallet_esplora_async/Cargo.toml
  examples/example_wallet_esplora_blocking/Cargo.toml
  examples/example_wallet_rpc/Cargo.toml
  wallet/Cargo.toml
  wallet/src/wallet/coin_selection.rs
  wallet/src/wallet/mod.rs
  wallet/src/wallet/params.rs
  wallet/src/wallet/tx_builder.rs
  wallet/tests/wallet.rs
Labels: dependencies

#249 Release 2.0.0-beta.0
  wallet/CHANGELOG.md
  wallet/Cargo.toml
Labels: release
