Repository bitcoindevkit/bdk_wallet, pull requests merged in 2025-07, with the labels that each got.

#265 Prefer Utxo::Local over Utxo::Foreign in OldestFirstCoinSelection
  wallet/src/wallet/coin_selection.rs
Labels: bug

#262 Preserve insertion order of manually selected utxos if `TxOrdering::Untouched`
  wallet/src/wallet/mod.rs
  wallet/src/wallet/tx_builder.rs
  wallet/tests/wallet.rs
Labels: bug

#258 feat: Add `exclude_unconfirmed` and `exclude_below_confirmations`
  wallet/src/wallet/tx_builder.rs
Labels: new feature

#284 Revert "clippy!: `Box` large enum variants"
  clippy.toml
  wallet/src/wallet/mod.rs
  wallet/src/wallet/persisted.rs
  wallet/tests/persisted_wallet.rs
Labels: chore
