Repository bitcoindevkit/bdk_wallet, pull requests merged in 2025-08, with the labels that each got.

#288 Fix `KeychainTxOutIndex` recovery logic when spk-cache is enabled
  wallet/src/wallet/mod.rs
  wallet/tests/persisted_wallet.rs
Labels: bug

#292 chore(deps): bump `bdk-chain` to `0.23.1`
  examples/example_wallet_electrum/Cargo.toml
  examples/example_wallet_esplora_async/Cargo.toml
  examples/example_wallet_esplora_blocking/Cargo.toml
  examples/example_wallet_rpc/Cargo.toml
  examples/example_wallet_rpc/src/main.rs
  wallet/Cargo.toml
  wallet/tests/wallet.rs
Labels: dependencies

#293 Release 2.1.0
  wallet/CHANGELOG.md
  wallet/Cargo.toml
Labels: release

#305 ci: bump rust-cache to 2.8.0
  .github/workflows/code_coverage.yml
  .github/workflows/cont_integration.yml
Labels: chore
